name: mirror-action
author: syzygy
description: This action allows you to mirror your github repo to other one
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  mirrorRepoUrl:
    desctipyion: 'mirror repo url of your mirror repository (ssh://)?(user@)?(domain)(:port)?(/|:)?(path).git'
    required: true
