name: Mirror repository

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        uses: syzygypl/mirror-action@master
        with:
          originSshKey: ${{ secrets.ORIGIN_REPO_SSH }}
          mirrorSshKey: ${{ secrets.MIRROR_REPO_SSH }}
          mirrorRepoUrl: 'git@github.com:syzygypl/mirror-action-mirror.git'
